### ISSUE TITLE
AWS Account Updates not reflected from Prowler

### ISSUE THREAD

**Issue by GaboP87** [prowler-cloud/prowler#108]
I just finished to run the prowler script after some modifications towards my AWS Account to be compliant. However, after some modifications on it, the prowler script is still showing me Users that do not exist anymore, or even WARNING messages for issues I just solved.
Specifically:
- I deleted an IAM User that appears as not having MFA enabled.
- I created CloudWatch Alarms for all the APIs that require monitoring for the given CloudWatch Logs LogGroup, and still receiving it as a WARNING.

Thanks,
Gabriel

**Comment by toniblyx** [comment]
Hi @GaboP87, thanks for your feedback. I think this is an expected behavior because all IAM credential checks are based on the IAM Credentials Report, if you see AWS documentation here (http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_getting-report.html?icmpid=docs_iam_console and message here https://console.aws.amazon.com/iam/home?region=us-east-2#/credential_report) you well see that after a report is created, it is stored for up to four hours. Despite prowler deletes the downloaded IAM creds report once it finishes, actually if you run prowler many times within 4 hours it will get the same report, hence, same results. 

If you check prowler more than 4 hours later you should see your actual results. Please, let me know if it doesn't to figure out what is going on.

**Comment by GaboP87** [comment]
Hi @toniblyx ,

Completely understood. I know what you are talking about so no worries. I just did not know how prowler was working underneath.

Cheers,
Gabriel

**Comment by toniblyx** [comment]
Thanks, good to see that is clear now, here you can see that part in the code:
https://github.com/Alfresco/prowler/blob/master/prowler#L401-L427
