### ISSUE TITLE
Remove check for ~/.aws/credentials file

### ISSUE THREAD

**Issue by chickenriggies** [prowler-cloud/prowler#144]
AWS credential files can live in arbitrary locations with the AWS_CONFIG_FILE environmental variable set. The conditional on lines 247-249 is not necessary.

```
  if [[ ! -f ~/.aws/credentials ]]; then
    echo -e "\n$RED ERROR!$NORMAL AWS credentials file not found (~/.aws/credentials). Run 'aws configure' first. \n"
    return 1
```

**Comment by toniblyx** [comment]
I'll do a test and let you know. It is supposed to work as you mention but this might be a bug.

**Comment by toniblyx** [comment]
Hi @hb3b, I'm checking this issue and I've found that doesn't work as expected but what I'm actually doing wrong is handling credentials in an EC2 instance with instance profile attached. In your case, instead of AWS_CONFIG_FILE I think it should be AWS_SHARED_CREDENTIALS_FILE. Can you share an example of the prowler command that your are running please?

**Comment by toniblyx** [comment]
Hi @hb3b, in PR #150 I have fixed this issue, you can check it out and let me know or open this issue again if you want. Thanks!
