### ISSUE TITLE
Add Support for Alpine?

### ISSUE THREAD

**Issue by ghost** [prowler-cloud/prowler#165]
bash-4.3# ./prowler 
Unknown Operating System

**Comment by toniblyx** [comment]
Hi @kxuanCeltik, that's because `bash` is not in Alpine, you can install it or use this Dockerfile as reference https://github.com/Alfresco/prowler/blob/master/Dockerfile

**Comment by ghost** [comment]
Like you can read:

[docker-alpine](https://github.com/kxuanCeltik/ServerTelegramBot/blob/docker-branch/Dockerfile-alpine)

I install bash.

Thanks

**Comment by toniblyx** [comment]
ooops! Sorry @kxuanCeltik I didn't read your question correctly. I'll check that link and see.

**Comment by toniblyx** [comment]
Ok, I get it, you need to change line:
https://github.com/Alfresco/prowler/blob/master/prowler#L170

To something like this:
`if [ "$OSTYPE" == "linux-gnu" ] || [ "$OSTYPE" == "linux-musl" ]; then`

- I have found other dependences like `curl`, so you need `apk add --update curl`
- also `mktemp` seems to work different, since Alpine uses the busybox version of mktemp, so it needs a tweak in line https://github.com/Alfresco/prowler/blob/master/prowler#L570, from this:
`TEMP_REPORT_FILE=$(mktemp -t prowler-${ACCOUNT_NUM}-XXXXX.cred_report )`
to
`TEMP_REPORT_FILE=$(mktemp -t -p /tmp prowler-${ACCOUNT_NUM}.cred_report-XXXXXX )`

Doing that change it works with both gnu and busybox mktemp.

I'm busy with other changes and checks, I will make this one later unless you want to send a PR. Thanks!!

**Comment by ghost** [comment]
Thanks !!!

It's Running
