### ISSUE TITLE
free license / commercial use version of prowler for companies

### ISSUE THREAD

**Issue by michael-paddle** [prowler-cloud/prowler#265]
I got prowler to play with based on a colleague's recommendation.  I really liked it, especially the simple / easy to follow report format but then I realised that we don't feel safe to use it due to the NC license even if we _might_ be okay due not "primarily" using this for commercial gain (rather safety).

I'd really appreciate if there was a version which simply stripped out the NC tests so that we could be sure we were safe using it.  This might be nicer / easier to maintain if that was the main version and then the NC tests can be easily (automatically?) downloaded if someone wants to use them.  

Even better would be if there were alternative tests which checked similar things.  I might be interested to have a look at this a bit later.  In the meantime, attached is the list of tests and groups of tests that would need to be removed or replaced.  

[deleted.txt](https://github.com/toniblyx/prowler/files/2580517/deleted.txt)

**Comment by toniblyx** [comment]
Hi @michael-paddle, thanks for your question and for using Prowler.

The NC CIS license only forces you to be CIS partner if you want to make money using Prowler checks that are over that license. If you just want to do hardening or assessment you are good to go. You can't just use those checks in the way they are redacted to make money.

You can create a custom group with only those checks you want, extras group is covered by Apache license.

To keep Prowler CIS compatible (I won't say compliance because implies other legal stuff) we have to keep those checks as they are. You can always fork Prowler and make your own version or variant and then send me a pull request, you may have had a good idea on getting rid/change of those checks to allow more flexibility, not sure about that but may depend on each use case. 

CIS is what it is, a number of good recommendations that I translated to AWS checks, that's why I added "extras", because there are many other things to check in AWS. Now (2.0-beta3) there are almost same amount of extra checks than CIS ones, so to change that CIS preference may change in the future. Not for 2.0 though.

**Comment by toniblyx** [comment]
Feel free to open this issue again if you have more questions regarding licenses.
