### ISSUE TITLE
Move main code to python calling checks as they are now allowing parallel checks and more

### ISSUE THREAD

**Issue by toniblyx** [prowler-cloud/prowler#267]
Moving the main base code to python (leaving checks in bash so far) would open up a world of possibilities to run parallel checks, improved and new output formats, easier multi-account support, integrations, etc.

Thanks to @rmogull for the idea.

**Comment by jtyers** [comment]
@toniblyx I'll take a look at this when I have time and open a PR. We've been using prowler to scan a handful of environments and it's clear that having the tool in Python would be really beneficial for speed and its overall robustness.

**Comment by toniblyx** [comment]
Hi @jtyers, thanks for your offer, it would be really helpful to start at least with the basics. I can create a new branch and you can PR to it. What do you think?

**Comment by jtyers** [comment]
@toniblyx yep sounds great to me :+1:

**Comment by toniblyx** [comment]
ok, here you go https://github.com/toniblyx/prowler/tree/python-devel. Looking forward to it!

**Comment by jtyers** [comment]
Just leaving an msg to say I am making progress. My fork has the latest code. `prowler.py` will now generate the IAM credential report and call the shell-script checks as before. One behaviourial difference I've put in is that errors caused by the checks will be sent to `stderr` rather than `stdout`, so that JSON parsing isn't disrupted in the face of errors.

As this is stlil calling the checks via shell, the Python prowler will have similar performance to the current one. The next stage after `prowler.py` is in place is to re-write the checks themselves in Python. This is where the performance gains will come.

**Comment by toniblyx** [comment]
Awesome! Thanks again. Even in python, performance is tricky here due to API rate limits but from there we can think about other options. Cheers!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toniblyx** [comment]
Hi @jtyers I've been testing your code a bit, it looks great! Let me know when you want to PR to devel-python and do a more extensive testing. Thanks!

**Comment by jtyers** [comment]
Heya, glad you like it! Apart from a few tweaks around the output, so make
it consistent with current prowler, I think this is nearly good to go. I've
tested some but not all checks against it.

**Comment by toniblyx** [comment]
Hey @jtyers I would like to PR your changes to `devel-python` and continue from there. What do you think?

**Comment by jtyers** [comment]
@toniblyx see above :-)

**Comment by toniblyx** [comment]
Thanks @jtyers I'll play with that code and see were we can go from there!

**Comment by museadmin** [comment]
Hi Guys,

I've been working a lot lately with NCCGroup on ScoutSuite, specifically around the issues they are facing with rate limiting. I thought I would share a few of my findings in the hope that they'll be helpful...

The recommended approach to-date seems to be to implement an incremental backoff AFTER detecting that you are being rate limited.

This is no good because by then, you might have caused an outage. Because AWS draws no distinction between a third party scanner like Prowler and their own services, you could interrupt an auto scaling group for example and cause it to fail mid stride. This is particularly troublesome in projects that have not reached a mature point in the SDLC and so don't have High Availability and resilience yet.

So by all means implement a multithreaded architecture, but do try to build in the ability to scale it right back to a single thread so that people can avoid exceeding the service limit.

I discuss this issue in more detail on this fork of mine - https://github.com/museadmin/botorate

Good luck!

**Comment by toniblyx** [comment]
Cool! Thanks for sharing that info @museadmin, I'll have a look

**Comment by lanhhuyet510** [comment]
I got the same ideal and I found a way to do this in bash.
it's technically not "multithreading", but this quick trick is good to me because I just need json output and I wrote another script to handle them. 

```sh
    for i in `seq 0 5 ${#CHECKS[@]}`; do
        execute_check ${CHECKS[i]} &
    
         for j in `seq 1 1 5`; do
            if [ $((i+j)) -lt ${#CHECKS[@] ]; then
                execute_check ${CHECKS[i+j]} &
            fi
         done
         wait
    done
```

**Comment by toniblyx** [comment]
I'm going to close this issue since the python support is going to be handle separately from this ticket.
