### ISSUE TITLE
Running Prowler inside AWS Lambda function

### ISSUE THREAD

**Issue by Sushant20** [prowler-cloud/prowler#293]
Did anybody try running prowler inside lambda function and dump the output to S3?

**Comment by markuman** [comment]
it's almost written in shell which wraps the aws cli.  
It might be easier to put it into a docker container and run it periodically inside fargate (serverless docker container).

**Comment by toniblyx** [comment]
Exactly, thanks @markuman. Even if you use a wrapper like the one I use for Wazuh, due to the lambda timeout it won’t work unless for quick checks. I didn’t think on the Fargate option, I think it is pretty smart. I’d like to see it working and document it sending json findings to s3 or splunk or elasticsearch. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sushant20** [comment]
Thanks @markuman @toniblyx  for the reply. Out of curiosity, how much time(average) does prowler need to run all the checks ? Will it be a good idea to use glue python shell for the same? We don't want to go ECS Fargate route for now.

**Comment by toniblyx** [comment]
It depends on how many resources you do have in each account you want to check or the number of checks or groups that you want to perform. It can be from few minutes to hours (10 or even more). Any checker that uses AWS API (like prowler using the cli) takes time due to the API request limits. See here https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html

Try running it manually first and get an idea of how long it takes in your case. 

Remember that you can always create your own group to check only what you need. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sushant20** [comment]
That makes sense !! Thanks a lot for your help @toniblyx

**Comment by markuman** [comment]
We run it now within our gitlab runner ci/cd process - also in a docker container- periodically and publish the result with gitlab pages.  
The only thing which needs to be handled is, that I need to catch the `prowler` exit 1 signal, when there is a `FAIL`. otherwhise gitlab won't publish the result on gitlab pages.

```Dockerfile
FROM alpine:3.9

RUN apk --update --no-cache add python3 bash curl
RUN pip3 install --upgrade pip
RUN pip install awscli ansi2html boto3
```

```yaml
variables:
  DOCKER_DRIVER: overlay

stages:
  - deploy

pages:
  image: ourimage:prowler
  stage: deploy
  script:
    - ./run.sh
  tags:
    - docker
  artifacts:
    paths:
      - public
  only:
    - automatic_calls
```

```shell
#!/bin/bash

mkdir -p public
/bin/bash prowler -r eu-central-1 -f eu-central-1 | ansi2html -la > public/index.html
exit 0
```

**Comment by toniblyx** [comment]
Thanks for sharing this info @markuman it is great. Do you have extended documentation available somewhere? I'd like to include it in the README.

**Comment by toniblyx** [comment]
I'm going to close this issue since I'll track this as a new feature/documentation in issue #299

**Comment by pingoleon108** [comment]
@Sushant20 I think that this is what you are looking for https://aws.amazon.com/blogs/security/use-aws-fargate-prowler-send-security-configuration-findings-about-aws-services-security-hub/
