### ISSUE TITLE
Reporting for 7.33 inconsistent?

### ISSUE THREAD

**Issue by mbode** [prowler-cloud/prowler#309]
For accounts without SAML providers, the result for check 7.33 is
```
7.33 [extra733] Check if there are SAML Providers then STS can be used (Not Scored) (Not part of CIS benchmark)
       FAIL! No SAML Provider found, add one and use STS
```
In other similiar scenarios, this is reported in `INFO`, e.g.
```
 7.28 [extra728] Check if SQS queues have Server Side Encryption enabled (Not Scored) (Not part of CIS benchmark)
       INFO! eu-north-1: No SQS queues found
```
Should 7.33 report as `INFO` instead of `FAIL` as well?

**Comment by toniblyx** [comment]
Yes, it makes sense. Usage of a SAML provider is a good practice but not having it is not a `FAIL` necessarily. I'm going to set it up as `INFO`

**Comment by toniblyx** [comment]
btw, I'll make that change in `devel` branch so far.

**Comment by nobodyme** [comment]
Not necessarily related to this issue, but what does that check mean?
`Check if there are SAML Providers then STS can be used`

Is it saying to use STS instead of SAML Providers? 
Any redirection to the concept would be appreciated. Thanks.

**Comment by toniblyx** [comment]
Hi @nobodyme, probably it is not properly written (please suggest anything better), what it means is that using SAML to authenticate your users, they will be attached to a role automatically therefore they use temporary tokens which is more secure than fixed API keys. No STS instead of SAML. That check just looks if you have SAML configured since to have it is a security best practice.
