### ISSUE TITLE
Filter on more than one region

### ISSUE THREAD

**Issue by cbchhaya** [prowler-cloud/prowler#359]
Currently, documentation for `-f` states 

> specify an AWS region to run checks against

However, [describe-regions](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-regions.html) takes multiple regions against `--region-names`. 

Can we do the same here as well?

**Comment by toniblyx** [comment]
Hi @cbchhaya, that option doesn't work properly across all checks, it is something that has to be improved. I'll label this issue accordingly to have it into account. In any case, it is not high priority since in most cases everybody wants to check all regions all the time to make sure you don't miss any resource.

**Comment by toniblyx** [comment]
Is this comma separated regions?
