### ISSUE TITLE
Check3x checks fail

### ISSUE THREAD

**Issue by vsMeecles** [prowler-cloud/prowler#409]
All Check3.x checks fail, when the necessary filters and alarms are actually in place. It seems to be an issue with incorrect regex

**Comment by zfLQ2qx2** [comment]
@toniblyx I was just going to open an issue for this myself then saw @vsMeecles issue. Checks 31-39, 310-314 look like great ideas, but probably copied from a third party source. Would it make sense to tell people how to set up whatever these checks are looking for? Or point people to something that does?

**Comment by toniblyx** [comment]
Hi @vsMeecles and @zfLQ2qx2 I agree those are the most controvert checks of CIS since there is not just one fixed way to set up those filters (at least until now with the remediaton suggestions), I don't use `group3` very often that's why I haven't put enough attention to it, sorry about that. @mastertinner made the latest contribution to this group of checks, I wonder if he has any comment to add here for more context. Additionally, @vsMeecles whould you mind to test these proposed changes? Looking at them they seem to be more accurate but I can't test them until next week. Thank you guys your support!

**Comment by cloudlena** [comment]
The changes I made include regexes that check for the specific implementation suggested by the [CIS Benchmark](https://d0.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf) so if you follow their remediation instructions carefully, Prowler should be happy. I think it's almost impossible to have generic regexes that check for all different ways of implementing these rules so I wouldn't diverge too much from the CIS rules. If we can make the rules a bit more lenient to include the most common implementation methods, that might be a good thing though. @vsMeecles, can you post your implementation of the rules as returned by the AWS API so that we can compare where the regexes lack leniency?

**Comment by vsMeecles** [comment]
Hi, I have attached the cloudformation template used implement these rules. When run against security hub, it shows all clean.

[securityhubcisalarms.yml.txt](https://github.com/toniblyx/prowler/files/3864693/securityhubcisalarms.yml.txt)

**Comment by cloudlena** [comment]
Hmm, I think that should work. The only thing I see is that your `FilterPattern`s are multi-line so maybe the regex parses them line by line and sees no match. Could you try moving all parts on one line and see if that fixes the problem?

As an example

```txt
{
  $.userIdentity.type = "Root" &&
  $.userIdentity.invokedBy NOT EXISTS &&
  $.eventType != "AwsServiceEvent"
}
```

to

```
{ $.userIdentity.type = "Root" && $.userIdentity.invokedBy NOT EXISTS && $.eventType != "AwsServiceEvent" }
```

If that is the actual problem, we should change the `check3x` function so that it concatenates the lines before running the regex.

**Comment by zfLQ2qx2** [comment]
@toniblyx @vsMeecles I raised a PR with instructions for setting up the checks and reference to the AWS CIS benchmark so people know the source. https://github.com/toniblyx/prowler/pull/410
I definitely see that there are a lot of ways to set up equivalent checks, maybe with the reference people will follow the style and order from the document to make the checks pass.

**Comment by zfLQ2qx2** [comment]
> If that is the actual problem, we should change the `check3x` function so that it concatenates the lines before running the regex.

Would be easy to go down the rabbit hole with this one. Do you verify the logical operators? Is it MFA == Yes or MFA != No, etc.

**Comment by zfLQ2qx2** [comment]
> Hi, I have attached the cloudformation template used implement these rules. When run against security hub, it shows all clean.

Very nice template, thank you!

**Comment by cloudlena** [comment]
> > If that is the actual problem, we should change the `check3x` function so that it concatenates the lines before running the regex.
> 
> Would be easy to go down the rabbit hole with this one. Do you verify the logical operators? Is it MFA == Yes or MFA != No, etc.

I absolutely agree. We shouldn't test for variations like the example you gave. The only place where it might make sense to be lenient is when it comes to whitespace. The current regexes already don't enforce any limitations regarding whitespace. The only thing that's currently not covered are line breaks like the ones @vsMeecles added. I think that might be a point where it makes sense to allow divergence because it will just lead to more legible filter rule definitions.

**Comment by toniblyx** [comment]
Thanks for your contribution guys, I think it makes sense to go ahead with  PR #410 since it comes with suggestions on how to properly set up those filters to pass. I will also add that CloudFormation template to the util folder to allow people to take advantage of our discussions here. Thanks again!

**Comment by toniblyx** [comment]
well, actually that yaml doesn't make it work due to the line break

**Comment by toniblyx** [comment]
Now it is better handled with the new additions from PR #410. Thanks!

**Comment by toniblyx** [comment]
Hey @zfLQ2qx2 I have noticed that all group3 checks fail when the CloudWatch Logs Log Group is not configured in CloudTrail. The output error on each `check3x` check is:

```
jq: error (at <stdin>:1): split input and separator must be strings
jq: error (at <stdin>:1): split input and separator must be strings
jq: error (at <stdin>:1): split input and separator must be strings
```

That seems to be due to these 3 lines here: https://github.com/toniblyx/prowler/blob/master/include/check3x#L24-L26. If there is not a LogGroup then that output is null and `jq` fails. It should be `textFail "No CloudWatch group found for CloudTrail events"`

BTW, I enhanced it changing `base64` using a multi OS function `decode_report` as mentioned https://github.com/toniblyx/prowler/issues/426

**Comment by toniblyx** [comment]
Actually in your PR #425 there is a change of the way I looked for CloudWatchLog Groups that was like here:
```
CLOUDWATCH_GROUP=$($AWSCLI cloudtrail describe-trails $PROFILE_OPT --region "$REGION" --query 'trailList[*].CloudWatchLogsLogGroupArn' --output text| tr '\011' '\012' | awk -F: '{print $7}')
```
and that PR chenged it to:
```
CLOUDWATCH_GROUPS=$(echo $DESCRIBE_TRAILS_CACHE | jq -r '.trailList[]|@base64')
```
Which is something totally different and makes `  if [[ $CLOUDWATCH_GROUPS != "" ]]; then` never work if  there are not Cloudwatchlog groups in place. Any feedback is welcome before I make any change to make it work back again. Thanks!

**Comment by JohnVonNeumann** [comment]
```
jq: error (at <stdin>:1): split input and separator must be strings
```
For All 3.x checks, I pulled from master yesterday.

**Comment by toniblyx** [comment]
Hi @JohnVonNeumann yes, that error happens when there are not CloudWatchLog Groups created. I have to fix it, I'm just waiting for feedback to better handle the error as described above. I'll fix it soon if there is no response. Sorry for any inconvenience.

**Comment by toniblyx** [comment]
OK, commit https://github.com/toniblyx/prowler/commit/b6e34adc248eac668be6a0b6273d550aca1cc997 fixes that issue. It might be a nicer way to fix it and reduce an API call though.

**Comment by JohnVonNeumann** [comment]
Will give it a whirl when I get into work!

**Comment by JohnVonNeumann** [comment]
From what I see it's all fixed, cheers @toniblyx, super quick turnaround, many props.

**Comment by toniblyx** [comment]
Cool, I'm closing it now.
