### ISSUE TITLE
A lot of jq errors in logs

### ISSUE THREAD

**Issue by lacteolus** [prowler-cloud/prowler#459]
Hi!
While scanning we receive the following sequence of errors in Prowler log:

An error occurred (AccessDenied) when calling the GetBucketAcl operation: Access Denied
An error occurred (AccessDenied) when calling the GetBucketLogging operation: Access Denied
jq: error (at <stdin>:1): split input and separator must be strings

The last one appears a lot (20-30 times) per scan. I'm not sure if these access issues and jq errors are related to each other. The only section in the resulting Prowler report showing Access Denied message is [extra734] for all our S3 buckets. 
Is it possible to debug the source of jq errors and verify if they are related to Access Denied errors? It seems not to affect resulting report but it is annoying to see dozens of them in log.

**Comment by zfLQ2qx2** [comment]
I see just one call to get-bucket-logging  https://github.com/toniblyx/prowler/blob/933e4152ccc554570f73e5ac5ff5737e3dc870aa/checks/check26#L30 which doesn't check for access denied and I see three places where get-bucket-acl is called with no check for access denied.

However, bigger issue might be why Prowler is getting access denied messages when accessing these buckets - is it not running with proper entitlements? Are these buckets in another account? Is there a bucket policy that denies calls to the bucket actions?

I've seen a case where someone locked down S3 buckets to the point that no tool could audit their configuration, if that is the case here you might need to add explicit permission for the prowler role  or allow the account in general to view the bucket configuration - neither get-bucket-acl nor get-bucket-logging leak anything significant.

**Comment by toniblyx** [comment]
I agree with @zfLQ2qx2, please make sure you are using proper permissions (https://github.com/toniblyx/prowler#custom-iam-policy) and check some of those bucket for implicit permissions that are preventing anything else to check them. In any case you can run prowler as `bash -x ./prowler -c <checkID>` to see where specifically is failing. Please, let us know how it goes in order to debug it better and better handle those errors to help others with the same situation. Thanks!
