### ISSUE TITLE
Root access keys usage (check11) only shows info

### ISSUE THREAD

**Issue by nimrodkor** [prowler-cloud/prowler#464]
I stumbled onto an account which has active access keys which are in use for the root user (very bad!).
I ran the scan, and found it only returns the following output:
`INFO! Root account last accessed (password key_1 key_2): 2019-12-05T09:34:55+00:00 2020-01-26T13:18:00+00:00 N/A`

Shouldn't it throw an error if there has been use in the last X days? maybe at least if there is use in the last day then throw a failure?

**Comment by zfLQ2qx2** [comment]
@toniblyx I think the issue here is that there isn't a good cross-platform way to work with dates in bash. GNU utilities can do it, but MacOS/*BSD/etc. often don't support those parameters. We know servers have python because the aws cli is python based, maybe a couple lines of Python for this check? I don't want to start a trend - its great that my most junior guy can read the check scripts and see whats happening and how to use the cli effectively - but maybe its necessary in this case?

**Comment by toniblyx** [comment]
I agree @nimrodkor, it should be a FAIL. That was probably the first check I wrote and didn't know how to better handle dates as I have done afterwards in other checks. @zfLQ2qx2 there are some functions that differentiates between Operating Systems (https://github.com/toniblyx/prowler/blob/master/include/os_detector#L20) and to handle dates, in this case this is just an incomplete check that should be rewritten.

**Comment by zfLQ2qx2** [comment]
@toniblyx I'll take a shot at a rewrite
