### ISSUE TITLE
Tag releases on docker hub

### ISSUE THREAD

**Issue by stone-z** [prowler-cloud/prowler#476]
Hello, first of all, thanks for this great resource.

I'm wondering if it would be possible to also tag individual releases on Docker Hub? It would help me with some CI integration.

**Comment by toniblyx** [comment]
Hi @stone-z, thanks for using Prowler.
I'm not doing releases very well, but I should, I know. That's why pulling latest is your best choice so far.

**Comment by stone-z** [comment]
Is this something I can help with? If you add a Dockerfile I'd be happy to set up a Github action or job for your preferred CI

**Comment by stone-z** [comment]
I went ahead and added something for this in https://github.com/toniblyx/prowler/pull/480

**Comment by toniblyx** [comment]
Hi @stone-z, that's is already done since long, an image is built every time there is a commit to master and it is done by Docker Hub. I thought you were asking for versions itself each time there is a build. I you go here https://hub.docker.com/r/toniblyx/prowler/builds you can see that it is built often based on this Dockerfile here https://github.com/toniblyx/prowler/blob/master/util/Dockerfile. Is that what you mean?

**Comment by stone-z** [comment]
I found the Dockerfile, I was just hoping to be able to pull a specific version of prowler instead of latest (for your already existing releases).

Like
`docker pull toniblyx/prowler:2.0`

Edit: So using the Docker Hub automatic builds I guess it just needs a build job on tags with some regex to match release tags

**Comment by lobobinario** [comment]
Hi @toniblyx,
In order to be able to keep stable a stage in a pipeline, it would be very useful to have a fixed version when pulling from dockerhub. 
This way we can test a version in a development pipeline and thus to be sure that an update won't  break anything.

**Comment by toniblyx** [comment]
you are right @lobobinario, I have to do better job when it comes to manage releases. With the given pace of improvements and additions it seems to be a good idea to cut a release weekly of bi-weekly instead of just merging all in to master without versions. I'm going to start this Friday with version 2.2, how does it sound?

**Comment by stone-z** [comment]
> it seems to be a good idea to cut a release weekly of bi-weekly

For me, the frequency isn't so much a problem, we just have to be able to use the exact version in a CI pipeline. Thank you for supporting this!

**Comment by lobobinario** [comment]
> you are right @lobobinario, I have to do better job when it comes to manage releases. With the given pace of improvements and additions it seems to be a good idea to cut a release weekly of bi-weekly instead of just merging all in to master without versions. I'm going to start this Friday with version 2.2, how does it sound?

Sounds good!!

**Comment by toniblyx** [comment]
This is achieved so far, it will be a new image tag for next versions.
