### ISSUE TITLE
False positives in check122

### ISSUE THREAD

**Issue by jamesgarfield** [prowler-cloud/prowler#478]
We're seeing several reports of IAM policies that allow for Full Administrative privileges, `Policy arn:aws:iam..... allows *:*`, for policies that don't upon manual inspection don't seem to match that warning.

An example policy that is being matched is
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "aws-portal:View*",
            "Resource": "*"
        },
        {
            "Effect": "Deny",
            "Action": "aws-portal:*Account",
            "Resource": "*"
        }
    ]
}
```

We've tried running the command invoked to do this check manually (https://github.com/toniblyx/prowler/blob/459a688b7a00cf62b1dd439874b6f622be1ace85/checks/check122#L25) on the offending policies, but when run that way they return nothing.

**Comment by toniblyx** [comment]
Hi @jamesgarfield, I'm not sure if I understood this. I tested your policy and in that case it doesn't catch that policy because of this filter `[?Effect == 'Allow' && Resource == '*' && Action == '*']"` so the action has to be `*` to be everything to everybody (full privileges). Do you have the latest version from master? I just used your policy.

**Comment by jamesgarfield** [comment]
I'll double check to make sure we're up to date

**Comment by jamesgarfield** [comment]
@toniblyx Sorry for the noise. It turns out we were using the latest tag (v2) which on closer inspection is super old. When I use the latest master this test passes fine.

Sorry again!

**Comment by toniblyx** [comment]
it's all right, thanks for using Prowler!
