### ISSUE TITLE
Enhance accuracy of extra758 shows EC2s running and not running for more than 12 months

### ISSUE THREAD

**Issue by angabini** [prowler-cloud/prowler#497]
The check queries based on Launch Time, which is the last time instance was powered on and not necessarily the time instance was launched for the first time. So it can be an instance that's older than 12 months (image, OS), but recently restarted.
If that's the intent of the check, better to be specific in the check's description.

**Comment by toniblyx** [comment]
I think it makes sense to count from the time it was launched fro the first time, isn't it? What do you think @gabrielsoltz ?

**Comment by toniblyx** [comment]
Since there is not other attribute to know when was the first time that an instance was launched (other than look at the AMI date and not necessarely the instance will be in the same state as the AMI) the only attribute to query is LaunchTime.

1st: this check currently looks for all instances instead of only the running ones, so it search for those running for 12 months or more even if they are stopped. This is not necessarely bad. However in FAIL state it says `       FAIL! us-west-2: EC2 Instance i-ABCDE running before than 2020-10-22` even if the instance is stopped. 

**FIX**: this FAIL output has to be accurate based on instace state.

**Comment by jfagoagas** [comment]
Hi @angabini we are closing this issue. This PR https://github.com/prowler-cloud/prowler/pull/1057 includes more granular information when an EC2 instance is stopped and it was launched more than a year ago.
