### ISSUE TITLE
check12 keeps failing

### ISSUE THREAD

**Issue by droppedpackets** [prowler-cloud/prowler#515]
Hi,
**[check12] Ensure multi-factor authentication (MFA) is enabled for all IAM users that have a console password (Scored)**
failed for one user when I ran the report first time. After that, updated the enabled the MFA device for said user and ran the group1 checks again, however, it keeps failing even though the console shows MFA device enabled.

**Comment by toniblyx** [comment]
Hi @droppedpackets that is because those checks are using the given credential report, AWS generates a credentials report every 4 hours so if you don't wait until then you won't see any change. Look at the third paragraph here https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_getting-report.html
