### ISSUE TITLE
Appetite for an All Python Version of Prowler?

### ISSUE THREAD

**Issue by chalbersma** [prowler-cloud/prowler#583]
Hey I've done some preliminary work in my branch on an engine that could consume yaml/json checks and do some of the checking necessary. Is there an appetite for an all python version of prowler?

**Comment by toniblyx** [comment]
Hi @chalbersma sure, that would be great, I can create a new branch and you can push your code there for testing. What do you think? Thanks!

**Comment by toniblyx** [comment]
btw, we have been thinking on the possibility to allow checks based on the AWSCLI in shell script and Boto3 with Python, that would be ideal to take advantage of the existing checks.

**Comment by deathbywedgie** [comment]
I would very, very much like an all Python version, and I'd be willing to help work on it. I'm wrapping Prowler with Python code for my own purposes as it is. :)

**Comment by marcjay** [comment]
I would also be keen for a movement towards python and boto, and keen to help with the work

**Comment by chalbersma** [comment]
Ya make a branch I'll push what I have in and you can take a look and see if it something that makes sense.

**Comment by toniblyx** [comment]
Ok, I'm going to create that branch from master. We have been already working on that but I don't know the actual status since @angabini has been doing some work on it, you can see his progress here https://github.com/toniblyx/prowler/projects/3 in both "To Do" and "In Progress".

To be honest, my first concern and priority on this would be support for checks in python. I know that if the core is in python it could be faster but that is not a problem today since the way it works now doesn't stress the API limits.

**Comment by toniblyx** [comment]
Here is the branch https://github.com/toniblyx/prowler/tree/python-devel

**Comment by chalbersma** [comment]
Cool I'll make a pull with what I've got so far.

**Comment by chalbersma** [comment]
https://github.com/toniblyx/prowler/pull/587

Made this. It's a reasonably large amount of stuff. `hunterkitty.py` (a prowler; cheesy joke) is the entry point for things and it assumes that the user has a profile that "works" to run checks against.

**Comment by toniblyx** [comment]
Going to close this one since this is not a priority at this point.
