### ISSUE TITLE
AWS S3 non-public Bucket showing as public in prowler report

### ISSUE THREAD

**Issue by S733** [prowler-cloud/prowler#635]
Hi,
In Prowler AWS S3 report buckets which are not public are showing as public. In S3 console the bucket access status is "Objects are not public", and also the "Block all public access" settings is enable for the the bucket. There are ten buckets in my account only two are public. But in prowler report all are showing as public. Below is the audit report 

default | 83******* | us-east-2 | 7.3 | FAIL | Not Scored | Extra | [extra73] Ensure there are no S3 buckets open to the Everyone or Any AWS user (Not Scored) (Not part of CIS benchmark) | us-east-2: s3-test-access bucket is Public!

**Comment by toniblyx** [comment]
Thanks @S733 can you please share more information about your buckets configuration? I can't reproduce it with the given info. Do you have ACLs or bucket policies attached to any of those buckets? btw, the report pasted seems to be truncated.

**Comment by S733** [comment]
@toniblyx I am running the following command to generate the report  

./prowler -g hipaa -M csv

Tested the same on another AWS account and got the same issue on private buckets. I'll attach some screenshots of one of the affected bucket.


![prowler-01](https://user-images.githubusercontent.com/48009625/87992677-669c8f00-cb06-11ea-9d67-37443fddac10.png)




![prowler-02](https://user-images.githubusercontent.com/48009625/87992698-6e5c3380-cb06-11ea-98e0-52b61ef8212c.png)




![prowler-03](https://user-images.githubusercontent.com/48009625/87992702-70be8d80-cb06-11ea-9273-25f6f6d82551.png)




![prowler-04](https://user-images.githubusercontent.com/48009625/87992709-7320e780-cb06-11ea-99c4-3ff92023c374.png)

**Comment by toniblyx** [comment]
Hi @S733, I didn't forget this ;)

I think this is due to the way the access error are handled by Prowler, you can get AccessDenied or UnauthorizedOperation when Prowler doesn't have permissions to perform  get-bucket-acl, get-public-access-block or get-bucket-policy-status. I have made a test and now if Prowler can't get acl, access block or policy status the check will fail telling that can't access but not saying that it is open.

Can you test it with this changes and let me know how it goes? Replace prowler/checks/check_extra73  with 
https://gist.github.com/toniblyx/208419b78f484e7066f7722aaa14a504

**Comment by toniblyx** [comment]
Error handling in this check was improved for  version 2.5 and no feedback was given with the provided code. @S733 feel free to reopen this issue if you think it is not solved. Thanks!
