### ISSUE TITLE
Creative Commons licenses for checks?

### ISSUE THREAD

**Issue by kapilt** [prowler-cloud/prowler#641]
Its very unusual to see Creative Commons used for software. Its actually not recommended by Creative Commons or most foundations/organizations to do so. Creative Commons explicitly recommends using a Software license for software https://creativecommons.org/about/program-areas/software/ and https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software .  Just curious is there any rationale on using Creative Commons here?

**Comment by kapilt** [comment]
My read of the Creative Commons license in use here is that this project is actually not opensource software per the OSI definition.

**Comment by toniblyx** [comment]
That is only for the piece of code part of the CIS recommendations due to the license and obligations of that particular AWS benchmark. Most of the code in Prowler is Apache (actually everything but the cis checks).

**Comment by toniblyx** [comment]
Do you have any specific motivation behind your question? I'm more than happy to clarify if you think the information here https://github.com/toniblyx/prowler#license is not clear enough. 

When [AWS_CIS_Foundations_Benchmark.pdf](https://d0.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf) was released, it had (and was one of the first ones released that way) Creative Commons license, if you look at that pdf now, it only has a reference to "Terms of Use" and there is no trace of any CC license there. In any case https://github.com/toniblyx/prowler#license clarifies that point since I released Prowler back in 2016. Please, feel free to reopen or comment this issue if you need more information.

**Comment by kapilt** [comment]
my motivation is ensuring that this project isn't misrepresenting itself as opensource due to a licensing mistake when it is currently not, due to a licensing misunderstanding. wrt to the standard, you're conflating the documentation license of the standard with the software in this repo's license wrt to those checks, the documentation license applies to the content of the documentation not the concepts implementation, there are many oss AWS CIS benchmark implementations. in general as alluded, the use of the creating commons license for sw is generally verboten. the additional restrictions there-in, do not make this repo as an aggregate work pass basic considerations of the OSI around what open source is.

**Comment by toniblyx** [comment]
I don't think there is any misrepresentation as Open Source, the fact that some checks were licensed as CC don't make Prowler not an Open Source project, as I mentioned, I used CC due to their legal restrictions by the time I released the code and they released the document, and was needed due to CIS constraints (that was discussed with them), and now looks like there is not such constraints. Hence a change in that code license may be done eventually, probably for the next release it would be all Apache.

Thanks for the head ups Kapil!
