### ISSUE TITLE
stranget error format i have ever seen ... 

### ISSUE THREAD

**Issue by royharoush** [prowler-cloud/prowler#744]
im using assume role with policies of readonlyacess and security audit. 
im seeing this error for some of the endpoints .. which i dont think are endpoints .. 
looks like a for loop gone crazy 
![image](https://user-images.githubusercontent.com/8113056/107222230-5524c100-6a1d-11eb-8a12-46279153a028.png)

**Comment by toniblyx** [comment]
Hi @royharoush, thanks for the heads up. Can you please share how are you running Prowler? Can you please also share the output of `bash -x ./prowler -c check42`, make sure you delete sensitive information from that output. That error can be due to permissions but the error in not being handled properly, I'm afraid.

**Comment by royharoush** [comment]
./prowler -A xxxxxx-R xxxxxx

This doesn't happen in the latest stable release, with exactly the same credentials and configuration.
only happens when I clone the master branch

**Comment by toniblyx** [comment]
Thanks for let me know, can you share the output of that command I mention in my comment? Just need to try to reproduce it to fix it.

**Comment by zfLQ2qx2** [comment]
@toniblyx in this case it looks like the person didn't have iam:describeregions permission, and the raw error message became the array of regions, and when this check runs the awscli is substituting those into the endpoint. I've done this myself trying to create a least privilege policy around prowler. I am pretty sure that one of my PRs puts a check around describe-regions to catch this - prowler will exit if describe-regions is unsuccessful because its hard to continue in any meaningful way if thats the case.

**Comment by toniblyx** [comment]
I guessed the same, that is why I asked for the debug output. I think your suggested changes were merged to handle that a bit better, not sure now if that was what I had to revert back.

**Comment by zfLQ2qx2** [comment]
@toniblyx Looks like it is merged - https://github.com/toniblyx/prowler/blob/6f371744dcafbc97d8de7cfcb9dad940a836cd35/prowler#L243 however its possible that not everyone has pulled the latest updates yet.

**Comment by zfLQ2qx2** [comment]
@toniblyx Aside - I think the only change of mine you reverted was the date handling for alpine which seemed to conflict with other busybox based distros - though I did come up with https://github.com/toniblyx/prowler/pull/736 that tries to solve the same problem by using jq for date parsing.

**Comment by royharoush** [comment]
this might be related to the time the token is issued to. the account i was querying was is very big, and the token for that account only lasts for 1 hour (in aws configuration), it's possible that token was already revoked and a new one had to be reissued to continue the querying.

**Comment by royharoush** [comment]
and it happend also with the EC2 API, that role is assigned with the right policies, so I dont think it's related to actual permissions. 
and yet again, it doesn't happen in the latest stable version.

**Comment by zfLQ2qx2** [comment]
@royharoush Try running Prowler with the -A -R -T parameters and it should take care of renewing the token before it expires.

**Comment by toniblyx** [comment]
this should be fixed now in branch 2.4, please feel free to test it and let me know.

**Comment by toniblyx** [comment]
This was already fixed back for 2.4.
