### ISSUE TITLE
Check 23 and Check 26 are failing when using centralised bucket 

### ISSUE THREAD

**Issue by capps1994** [prowler-cloud/prowler#753]
We have a centralised bucket for our CloudTrail logs that is only accessible from CloudTrail for putObject within our organisation, therefore we get access denied on check 23 and 26 before this used to give us an Info message, now it's just giving us a fail. 

if the check is getting access denied the bucket is not publicly accessible.

I think I have found the PR that is causing the issue [here](https://github.com/toniblyx/prowler/pull/729/commits/de87de3b39b4d8de2d1f0bebd6cfbaf9f18e7ba2)

**Comment by toniblyx** [comment]
Hi @capps1994, I get what you mean, @zfLQ2qx2 made that change and I knew it could be a bit controversial. What is better in that case? To get info message saying that can't tell you the truth because Prowler can't get the configuration bit or give you a fail and you have to look at it and, if needed, you can add that resource to a whitelist? I think I prefer the whitelist option, I mean, to get to know the case then to whitelist that FAIL. What do you guys think?

**Comment by capps1994** [comment]
Thanks for getting back quickly, I think the whitelist option may work for us. We'll try it and let you know

**Comment by capps1994** [comment]
We went with the whitelist approach, that that is working as expected now.

**Comment by toniblyx** [comment]
awesome, thanks for let me know.
