### ISSUE TITLE
Enhance extra768: didn't find plain-text password in variables in other place than taskDefinition.containerDefinitions.environment

### ISSUE THREAD

**Issue by seffparker** [prowler-cloud/prowler#826]
I have ENV variables that inject into ECS Tasks during container run-phase via the Task Definition. Those variable-value pairs including AWS_SECRET, DB_PASSWORD etc are defined as PLAIN_TEXT rather than pulling from SSM Parameter Store.

I think it should be reported as Security Risk, rather than PASS:
```
 7.68 [extra768] Find secrets in ECS task definitions variables (Not Scored) (Not part of CIS benchmark)    
       PASS! REGION: No secrets found in ECS task definition TASK_DEF_NAME:VERSION variables
```

**Comment by toniblyx** [comment]
Thanks for let me know. Prowler uses a tool called detect-secrets underneath and it has some [config options](https://github.com/toniblyx/prowler/blob/583cffaefb067e8fbd81a5300db11a0a841102b2/include/secrets_detector#L27-L32) to be more or less sensible when it comes to detect secrets. Additionally, latest version of detect-secrets seems to work weird, so please try with this workaround and let me know if it gets something else https://github.com/toniblyx/prowler/issues/806#issuecomment-856733643. Could you share an example of those not detected secrets to have an idea? Share something similar, not your secrets ;)

**Comment by seffparker** [comment]
These are the few KEY-VALUE Environment Variable pairs present in ECS Container Definition that didn't detect by Prawler  v2.4.0-07042021
```
AWS_ACCESS_ID = "AKIAZFFYKAOLF___masked___"
AWS_SECRET = "ZzkJpc6Ef378___masked___upuZ8aLr/GdXT"
POSTGRES_PASSWORD = "fxYdlh3a2___masked___UvAw7q"
```

As per this https://github.com/toniblyx/prowler/issues/806#issuecomment-856733643 I have tried to downgrade the detect-secrets into v1.0.3, but same behaviour. 

I have also tried after setting `BASE64_LIMIT` and `HEX_LIMIT` into (0.0, 0.0) and (8.0, 8.0), but still the same.

**Comment by w0rmr1d3r** [comment]
I think I've found the isssue!

For container definitions, there are 2 different sections, one for environment variables and another one for secrets.
In the AWS console, both are merged into the same section (Environment variables), but when downloading the task definition with:
```
aws ecs  describe-task-definition --task-definition YOUR-TASK
```
And take a look at the output, both sections appear separately.

But in Prowler, in that very same check, that query is filtered like this:
```
aws ecs  describe-task-definition --task-definition YOUR-TASK --query 'taskDefinition.containerDefinitions[*].environment'
```

Which only outputs the environment variables, not the secrets section.
If your secrets are defined in the `secrets` section, it won't be detected by Prowler.

**Comment by toniblyx** [comment]
Exactly,  here is the line that saves those variable in a temp file to analyze with detect-secrets https://github.com/toniblyx/prowler/blob/master/checks/check_extra768#L44 

@seffparker  you can run Prowler with `bash -x ./prowler -c extra768 -f <region>` and see exactly that line running. Can you confirm if those variables are in that command output?

**Comment by w0rmr1d3r** [comment]
Hello @toniblyx  and @seffparker !
I was wondering, AWS recommends to put secrets (form SSM or Secrets Manager) in the container secrets section within the task definition.
More about what I said some weeks ago -> https://github.com/toniblyx/prowler/issues/826#issuecomment-866907723
Checking this AWS documentation:
* https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-secrets.html#secrets-create-taskdefinition
* https://aws.amazon.com/premiumsupport/knowledge-center/ecs-data-security-container-task/
AWS recommends to pass secrets, but in the form of resources in the SSM Parameter Store or Secrets Manager. However, the issue @seffparker has (or had, don't know) is that, those secrets (in the correct part of the definition) are plain text and not ARN.

Modifying the query will solve the issue but will bring more problems, since if I resolve secrets by passing the ARN, they will be detected but are correctly placed.
If we do modify the query, those findings should be filtered and scanned so they do not belong to an ARN.

What do you guys think?

**Comment by w0rmr1d3r** [comment]
Updated a little bit that check for now, so it's clearer on what does it do PR -> https://github.com/toniblyx/prowler/pull/853

**Comment by toniblyx** [comment]
I'm reviewing this issue again and I don't quite understand where are those variable stored in the task definition. @seffparker Container variables are stored in `taskDefinition.containerDefinitions.environment`, where do you place those credentials in `taskDefinition.containerDefinitions.requiresAttributes`?

**Comment by seffparker** [comment]
> I'm reviewing this issue again and I don't quite understand where are those variable stored in the task definition. @seffparker Container variables are stored in `taskDefinition.containerDefinitions.environment`, where do you place those credentials in `taskDefinition.containerDefinitions.requiresAttributes`?

I'm quite not sure about the path in an IaaC. But in GUI, these variables are set at AWS > ECS > Task Definition > Container > Environment Variables.

**Comment by toniblyx** [comment]
That is exactly what this is `taskDefinition.containerDefinitions.environment`
![Screenshot 2021-11-05 at 18 49 53](https://user-images.githubusercontent.com/3985464/140555909-597d55ff-5252-4f90-bd65-31357ca8ed84.png) 

Is it there where you have those variables?

**Comment by seffparker** [comment]
> That is exactly what this is `taskDefinition.containerDefinitions.environment` ![Screenshot 2021-11-05 at 18 49 53](https://user-images.githubusercontent.com/3985464/140555909-597d55ff-5252-4f90-bd65-31357ca8ed84.png)
> 
> Is it there where you have those variables?

Yes.

**Comment by w0rmr1d3r** [comment]
Hello @toniblyx and @seffparker !

If I'm not wrong, in that section of the task definition (or container definition) they appear your environment variables (plain text) as well as your secrets (arn).
Quoting part of this answer -> https://github.com/toniblyx/prowler/issues/826#issuecomment-902718387
> AWS recommends to put secrets (form SSM or Secrets Manager) in the container secrets section within the task definition.

Either if you put your secrets as environment variables (bad) or as secrets (good), they will appear (both variables and secrets) in that very same section. However, Prowler is only scanning in that environment section. Good that it's scanning there, since secrets shouldn't be there.

Regarding Cloudformation, for a container definition, we should put secrets here:
https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-secrets

And not here (AWS even puts a warning in that section):
https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-environment

At the same time, Prowler could scan for secrets in the secrets section, and if the detected secret is not an arn, it should fail the check.

Hope it clarifies something :)

**Comment by jfagoagas** [comment]
Hi all, we're closing this issue for the following reasons:
- Right now Prowler check [extra768](https://github.com/prowler-cloud/prowler/blob/2.9.0/checks/check_extra768) analyzes if some secret is present in a ECS Task Definition. (`taskDefinition.containerDefinitions.environment` section).
- Every value included in the `taskDefinition.containerDefinitions.secrets` must only be a Secrets Manager or SSM Parameter Store ARN (Rationale: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-secret.html#aws-properties-ecs-taskdefinition-secret-properties).
![Screenshot 2022-04-20 at 12 26 30](https://user-images.githubusercontent.com/16007882/164210992-e591f8f2-335c-4532-a956-ec6281861bc0.png)

So, it is not possible to include some plaintext secret in the `ContainerDefinition.Secrets` section.
