### ISSUE TITLE
.asff-json now .asff.json

### ISSUE THREAD

**Issue by mascarim9** [prowler-cloud/prowler#850]
Noticed that the SecurityHub integration in 2.5 switched from .asff-json to .asff.json. Is that by design? 

Its causing issues with s3/lambda invocations that are based on file path. I edited the source code in `prowler/include/outputs` locally back and everything is working fine. Just wondering

**Comment by toniblyx** [comment]
Hi @mascarim9, that file name change doesn't actually impacts the Security Hub integration. The file name change is actually done for the QuickSight integration, for the dataset configuration (not public yet). Can you please give me more details about those lambda invocations?

**Comment by mascarim9** [comment]
we have a lambda function that was triggered by an s3 put from the .json outputs so it was easy to prevent .asff-json from triggering it.  Our workaround was using aws s3 mv to get the asff.json file out of the output/ directory before moving the files out of the container to begin the rest of the work flow.

**Comment by claviston** [comment]
Hello Colleagues, 

I am facing this kind of issue when I run the stack to create a Codebuild report. 

any idea how to fix it?

<html>
<body>


[Container] 2021/08/19 20:01:28 Command did not exit successfully ./prowler $PROWLER_OPTIONS exit status 3
--
974 | [Container] 2021/08/19 20:01:28 Phase complete: BUILD State: FAILED
**_975_ | [Container] 2021/08/19 20:01:28 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: ./prowler $PROWLER_OPTIONS. Reason: exit status 3**
976 | [Container] 2021/08/19 20:01:28 Entering phase POST_BUILD
977 | [Container] 2021/08/19 20:01:28 Running command echo "Uploading reports to S3..."


</body>
</html>
![prowler-error](https://user-images.githubusercontent.com/57537626/130274700-05e8284a-6dac-4547-a5bc-f53e8a65d0ec.jpg)

**Comment by mascarim9** [comment]
can you paste the value of the $PROWLER_OPTIONS please

its probably your -M if running in CodeBuild, you need to have the junit-xml i believe

**Comment by claviston** [comment]
<html>
<body>


_ __  _ __ _____      _\| \| ___ _ __
--
943 | \| '_ \\| '__/ _ \ \ /\ / / \|/ _ \ '__\|
944 | \| \|_) \| \| \| (_) \ V  V /\| \|  __/ \|
945 | \| .__/\|_\|  \___/ \_/\_/ \|_\|\___\|_\|v2.5.0-12August2021
946 | \|_\| the handy cloud security tool
947 |  
948 | Date: Thu Aug 19 20:01:25 UTC 2021
949 |  
950 | Writing JUnit XML reports to ./junit-reports
951 | Generating AWS IAM Credential Report... -  []
952 | 1.1 [check11] Avoid the use of the root account - iam [High]
953 | PASS! us-east-1: Root user in the account wasn't accessed in the last 1 days
954 | 1.2 [check12] Ensure multi-factor authentication (MFA) is enabled for all IAM users that have a console password - iam [High]
955 | FAIL! us-east-1: User swo has Password enabled but MFA disabled
956 | FAIL! us-east-1: User swo3 has Password enabled but MFA disabled
957 | FAIL! us-east-1: User swo4 has Password enabled but MFA disabled
958 | 1.3 [check13] Ensure credentials unused for 90 days or greater are disabled - iam [Medium]
959 | PASS! us-east-1: User swo has logged into the console in the past 90 days
960 | PASS! us-east-1: User swo1 has logged into the console in the past 90 days
961 | INFO! us-east-1: User swo2 has not logged into the console since creation
962 | INFO! us-east-1: User swo3 has not logged into the console since creation
963 | INFO! us-east-1: User swo4 has not logged into the console since creation
964 | PASS! us-east-1: User <root_account> has used access key 1 in the past 90 days
965 | PASS! us-east-1: User swo1 has used access key 1 in the past 90 days
966 | PASS! us-east-1: User swo4 has used access key 1 in the past 90 days
967 | PASS! us-east-1: User swo1 has used access key 2 in the past 90 days
968 | PASS! us-east-1: User swo2 has used access key 2 in the past 90 days
969 | 1.4 [check14] Ensure access keys are rotated every 90 days or less - iam [Medium]
970 | FAIL! us-east-1: <root_account> has not rotated access key 1 in over 90 days
971 | PASS! us-east-1: No users with access key 2 older than 90 days
972 |  
973 | **[Container] 2021/08/19 20:01:28 Command did not exit successfully ./prowler $PROWLER_OPTIONS exit status 3**
974 | [Container] 2021/08/19 20:01:28 Phase complete: BUILD State: FAILED
975 | [Container] 2021/08/19 20:01:28 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: ./prowler $PROWLER_OPTIONS. Reason: exit status 3
976 | [Container] 2021/08/19 20:01:28 Entering phase POST_BUILD
977 | [Container] 2021/08/19 20:01:28 Running command echo "Uploading reports to S3..."
978 | Uploading reports to S3...
979 |  
980 | [Container] 2021/08/19 20:01:28 Running command aws s3 cp --sse AES256 output/ s3://$BUCKET_REPORT/ --recursive
981 | Completed 12.4 KiB/48.9 KiB (133.2 KiB/s) with 3 file(s) remaining
982 | upload: output/prowler-output-534444159294-20210819200125.csv to s3://prowler-reports-us-east-1-prowler-534444159294/prowler-output-534444159294-20210819200125.csv
983 | Completed 12.4 KiB/48.9 KiB (133.2 KiB/s) with 2 file(s) remaining
984 | Completed 26.7 KiB/48.9 KiB (284.5 KiB/s) with 2 file(s) remaining
985 | upload: output/prowler-output-534444159294-20210819200125.json to s3://prowler-reports-us-east-1-prowler-534444159294/prowler-output-534444159294-20210819200125.json
986 | Completed 26.7 KiB/48.9 KiB (284.5 KiB/s) with 1 file(s) remaining
987 | Completed 48.9 KiB/48.9 KiB (467.6 KiB/s) with 1 file(s) remaining
988 | upload: output/prowler-output-534444159294-20210819200125.html to s3://prowler-reports-us-east-1-prowler-534444159294/prowler-output-534444159294-20210819200125.html
989 |  
990 | [Container] 2021/08/19 20:01:28 Running command echo "Done!"
991 | Done!
992 |  
993 | [Container] 2021/08/19 20:01:28 Phase complete: POST_BUILD State: SUCCEEDED
994 | [Container] 2021/08/19 20:01:28 Phase context status code:  Message:
995 | [Container] 2021/08/19 20:01:28 Preparing to copy TEST report prowler
996 | [Container] 2021/08/19 20:01:28 Expanding base directory path:  prowler/junit-reports
997 | [Container] 2021/08/19 20:01:28 Assembling file list
998 | [Container] 2021/08/19 20:01:28 Expanding prowler/junit-reports
999 | [Container] 2021/08/19 20:01:28 Expanding file paths for base directory prowler/junit-reports
1000 | [Container] 2021/08/19 20:01:28 Assembling file list
1001 | [Container] 2021/08/19 20:01:28 Expanding **/*
1002 | [Container] 2021/08/19 20:01:28 Found 4 file(s)
1003 | [Container] 2021/08/19 20:01:28 Report export config is NO_EXPORT, skip exporting reports
1004 | [Container] 2021/08/19 20:01:28 Phase complete: UPLOAD_ARTIFACTS State: SUCCEEDED
1005 | [Container] 2021/08/19 20:01:28 Phase context status code:  Message:


</body>
</html>

**Comment by claviston** [comment]
I am using the last cloudformation template available 

arn:aws:cloudformation:us-east-1:11111111111:stack/Prowler/3080ef70-fde0-11eb-8b2e-0a903255f0c5

**Comment by w0rmr1d3r** [comment]
@claviston I can't see your `$PROWLER_OPTIONS` that @mascarim9 asked.

Can you paste them here? Have I missed something?

Thank you!

**Comment by claviston** [comment]
Hello @mascarin9

there you the print I have here,  If there is another way to find out what
you need please let me know
[image: image.png]

**Comment by w0rmr1d3r** [comment]
Sorry @claviston , I see you replied via email, but I can't see the image you attached

**Comment by claviston** [comment]
> can you paste the value of the $PROWLER_OPTIONS please
> 
> its probably your -M if running in CodeBuild, you need to have the junit-xml i believe

Hello @mascarim9  can you send your email to x529828@gmail.com and I will setup a call on google meeting where I can share the screen with you and you can check the information I have problem to share.

thank you

**Comment by claviston** [comment]
> @claviston I can't see your `$PROWLER_OPTIONS` that @mascarim9 asked.
> 
> Can you paste them here? Have I missed something?
> 
> Thank you!

Hello Dear, this is the print I got here, I got this from code build logs, if this is not what you expect to have please instruct me how to get it or send me your email address to x529828@gmail.com then I can set up a session and share the screen with you. 

![image](https://user-images.githubusercontent.com/57537626/130614982-c1d1eb6c-4509-4183-a58b-62fca97c1a09.png)

**Comment by claviston** [comment]
Additionally, I run the same cloudformation to create the code build report in another Aws account and there is the same problem , just to let you know. 

![image](https://user-images.githubusercontent.com/57537626/130615583-aaf25a3a-cb6d-418b-b1df-2f8b84a114db.png)

**Comment by toniblyx** [comment]
Thanks for reporting it @claviston, this should be taken as a separate issue, it is not related to the extension name change. In any case, please go to the stack in CloudFormation and let us know what is the value of the `ProwlerOptions` in the Parameters tab. But please, in a new issue. Thanks!

@mascarim9 please give a look to the new `-B` option to make prowler send the reports to a s3 bucket directly. It uses specific folders based on the format https://github.com/toniblyx/prowler/blob/master/include/outputs_bucket#L36-L57.

**Comment by claviston** [comment]
> Thanks for reporting it @claviston, this should be taken as a separate issue, it is not related to the extension name change. In any case, please go to the stack in CloudFormation and let us know what is the value of the `ProwlerOptions` in the Parameters tab. But please, in a new issue. Thanks!
> 
> @mascarim9 please give a look to the new `-B` option to make prowler send the reports to a s3 bucket directly. It uses specific folders based on the format https://github.com/toniblyx/prowler/blob/master/include/outputs_bucket#L36-L57.
![image](https://user-images.githubusercontent.com/57537626/130623945-f8492566-e8be-49cd-b249-89138634fbd4.png)

**Comment by claviston** [comment]
> > Thanks for reporting it @claviston, this should be taken as a separate issue, it is not related to the extension name change. In any case, please go to the stack in CloudFormation and let us know what is the value of the `ProwlerOptions` in the Parameters tab. But please, in a new issue. Thanks!
> > @mascarim9 please give a look to the new `-B` option to make prowler send the reports to a s3 bucket directly. It uses specific folders based on the format https://github.com/toniblyx/prowler/blob/master/include/outputs_bucket#L36-L57.
> > ![image](https://user-images.githubusercontent.com/57537626/130623945-f8492566-e8be-49cd-b249-89138634fbd4.png)

this is from another was account 
![image](https://user-images.githubusercontent.com/57537626/130624947-3a1649b1-c129-4736-b7e6-4f9267f3a69a.png)

**Comment by zeako** [comment]
@toniblyx this change should be noted in version `2.5.0` release notes.
